In [61]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/student-data.json"
df = pd.read_json(url)

#by default ascending
df.sort_values("english")

# descending
df.sort_values("english", ascending=False)

#by default ascending method
df.sort_values(by=["english","maths"],ascending=[False,True])

#
df.sort_values("name")

#a to z
df["name"] = df["name"].str.lower()
df.sort_values("name")

#add column total
df["total"] = df['english']+df['maths']+df['physics']
df

#add row
df.loc[14] = ["danish",'Male',50,80,80,210]
df

#delete column
df.drop("total",axis=1)


#delete row
df.drop(14,axis=0)


df.drop([6,7,8,9,10,11,12,13,14],inplace=True)
df

df["doj"] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05','2025-06-06']
df

      name  gender  physics  maths  english  total         doj
0     arun    Male       88     87       78    253  2025-01-01
1   rajesh    Male       96    100       95    291  2025-02-02
2  moorthy    Male       89     90       70    249  2025-03-03
3     raja    Male       30     25       40     95  2025-04-04
4     usha  Female       67     45       78    190  2025-05-05
5    priya  Female       56     46       78    180  2025-06-06

In [62]:
import pandas as pd
url = "https://raw.githubusercontent.com/rajendra0968jangid/Ds-Arya/main/file2.json"
df = pd.read_json(url)
df["doj"] = ['2025-01-01','2025-02-02','2025-03-03','2025-04-04','2025-05-05']
df["doj"].dtype


# convert string to date
df["doj"] =pd.to_datetime(df["doj"])
df["doj"].dtype
#date operation
df["doj"].dt.year
df["doj"].dt.month
df["doj"].dt.day
df["doj"].dt.day_name()

#20 days
df["doj"] + pd.to_timedelta("20 days")

0   2025-01-21
1   2025-02-22
2   2025-03-23
3   2025-04-24
4   2025-05-25
Name: doj, dtype: datetime64[ns]